#!/bin/bash --login

#SBATCH -o DEFAULT.%A_%a.out
#SBATCH -J DEFAULT

#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --ntasks-per-core=1
#SBATCH --hint=nomultithread
#SBATCH --mem-per-cpu=200

#SBATCH --time=2-00:00:00
#SBATCH -p main
#SBATCH --qos=standard

#SBATCH --mail-type=ALL

#SBATCH --array=1478,1480

module add ORCA/4.2.0-OpenMPI-3.1.4

export SOURCEDIR=`pwd`
export SCRDIR=/localscratch/${USER}/${SLURM_JOB_ID}_${SLURM_ARRAY_TASK_ID}

orca_input_file=run

clean_up() {
   cd ${JOBDIR}
   cp -f  ${SCRDIR}/* ${JOBDIR} &> /dev/null
   rm -rf ${SCRDIR}
   rm -f  ${JOBDIR}/tempdir
}

cd conformer-${SLURM_ARRAY_TASK_ID}
sed -i "s/nprocs.*/nprocs ${SLURM_NTASKS}/" ${orca_input_file}
sed -i "s/maxcore.*/maxcore ${SLURM_MEM_PER_CPU}/" ${orca_input_file}
export JOBDIR=`pwd`
mkdir -p ${SCRDIR}
cp * ${SCRDIR}
ln -s ${SCRDIR} ${JOBDIR}/tempdir

trap clean_up EXIT INT TERM
cd ${SCRDIR}
orcarun=`which orca`
${orcarun} ${orca_input_file} >> ${JOBDIR}/${orca_input_file}.out 2>> ${JOBDIR}/${orca_input_file}.out


